/*
 * This file is generated by jOOQ.
 */
package com.uptosmth.chronos.db;

import com.uptosmth.chronos.db.tables.Activity;
import com.uptosmth.chronos.db.tables.BrowserActivity;
import com.uptosmth.chronos.db.tables.EditorActivity;
import com.uptosmth.chronos.db.tables.Heartbeat;
import com.uptosmth.chronos.db.tables.MeetingActivity;
import com.uptosmth.chronos.db.tables.SqliteSequence;
import com.uptosmth.chronos.db.tables.WindowActivity;

/** Convenience access to all tables in the default schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /** The table <code>activity</code>. */
    public static final Activity ACTIVITY = Activity.ACTIVITY;

    /** The table <code>browser_activity</code>. */
    public static final BrowserActivity BROWSER_ACTIVITY = BrowserActivity.BROWSER_ACTIVITY;

    /** The table <code>editor_activity</code>. */
    public static final EditorActivity EDITOR_ACTIVITY = EditorActivity.EDITOR_ACTIVITY;

    /** The table <code>heartbeat</code>. */
    public static final Heartbeat HEARTBEAT = Heartbeat.HEARTBEAT;

    /** The table <code>meeting_activity</code>. */
    public static final MeetingActivity MEETING_ACTIVITY = MeetingActivity.MEETING_ACTIVITY;

    /** The table <code>sqlite_sequence</code>. */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /** The table <code>window_activity</code>. */
    public static final WindowActivity WINDOW_ACTIVITY = WindowActivity.WINDOW_ACTIVITY;
}
