/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uptosmth_chronos_infra_X11WindowManager */

#ifndef _Included_com_uptosmth_chronos_infra_X11WindowManager
#define _Included_com_uptosmth_chronos_infra_X11WindowManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uptosmth_chronos_infra_X11WindowManager
 * Method:    getIdleMilli
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_uptosmth_chronos_infra_X11WindowManager_getIdleMilli
  (JNIEnv *, jobject);

/*
 * Class:     com_uptosmth_chronos_infra_X11WindowManager
 * Method:    isAway
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_uptosmth_chronos_infra_X11WindowManager_isAway
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
