/*
 * This file is generated by jOOQ.
 */
package com.uptosmth.chronos.db.tables.records;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import com.uptosmth.chronos.db.tables.BrowserActivity;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BrowserActivityRecord extends UpdatableRecordImpl<BrowserActivityRecord>
        implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /** Setter for <code>browser_activity.id</code>. */
    public void setId(Integer value) {
        set(0, value);
    }

    /** Getter for <code>browser_activity.id</code>. */
    public Integer getId() {
        return (Integer) get(0);
    }

    /** Setter for <code>browser_activity.title</code>. */
    public void setTitle(String value) {
        set(1, value);
    }

    /** Getter for <code>browser_activity.title</code>. */
    public String getTitle() {
        return (String) get(1);
    }

    /** Setter for <code>browser_activity.url</code>. */
    public void setUrl(String value) {
        set(2, value);
    }

    /** Getter for <code>browser_activity.url</code>. */
    public String getUrl() {
        return (String) get(2);
    }

    /** Setter for <code>browser_activity.url_domain</code>. */
    public void setUrlDomain(String value) {
        set(3, value);
    }

    /** Getter for <code>browser_activity.url_domain</code>. */
    public String getUrlDomain() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BrowserActivity.BROWSER_ACTIVITY.ID;
    }

    @Override
    public Field<String> field2() {
        return BrowserActivity.BROWSER_ACTIVITY.TITLE;
    }

    @Override
    public Field<String> field3() {
        return BrowserActivity.BROWSER_ACTIVITY.URL;
    }

    @Override
    public Field<String> field4() {
        return BrowserActivity.BROWSER_ACTIVITY.URL_DOMAIN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public String component4() {
        return getUrlDomain();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public String value4() {
        return getUrlDomain();
    }

    @Override
    public BrowserActivityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BrowserActivityRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BrowserActivityRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public BrowserActivityRecord value4(String value) {
        setUrlDomain(value);
        return this;
    }

    @Override
    public BrowserActivityRecord values(
            Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /** Create a detached BrowserActivityRecord */
    public BrowserActivityRecord() {
        super(BrowserActivity.BROWSER_ACTIVITY);
    }

    /** Create a detached, initialised BrowserActivityRecord */
    public BrowserActivityRecord(Integer id, String title, String url, String urlDomain) {
        super(BrowserActivity.BROWSER_ACTIVITY);

        setId(id);
        setTitle(title);
        setUrl(url);
        setUrlDomain(urlDomain);
    }
}
