/*
 * This file is generated by jOOQ.
 */
package com.uptosmth.chronos.db.tables;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import com.uptosmth.chronos.db.DefaultSchema;
import com.uptosmth.chronos.db.Keys;
import com.uptosmth.chronos.db.tables.records.MeetingActivityRecord;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MeetingActivity extends TableImpl<MeetingActivityRecord> {

    private static final long serialVersionUID = 1L;

    /** The reference instance of <code>meeting_activity</code> */
    public static final MeetingActivity MEETING_ACTIVITY = new MeetingActivity();

    /** The class holding records for this type */
    @Override
    public Class<MeetingActivityRecord> getRecordType() {
        return MeetingActivityRecord.class;
    }

    /** The column <code>meeting_activity.id</code>. */
    public final TableField<MeetingActivityRecord, Integer> ID =
            createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /** The column <code>meeting_activity.application</code>. */
    public final TableField<MeetingActivityRecord, String> APPLICATION =
            createField(DSL.name("application"), SQLDataType.CLOB.nullable(false), this, "");

    private MeetingActivity(Name alias, Table<MeetingActivityRecord> aliased) {
        this(alias, aliased, null);
    }

    private MeetingActivity(
            Name alias, Table<MeetingActivityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /** Create an aliased <code>meeting_activity</code> table reference */
    public MeetingActivity(String alias) {
        this(DSL.name(alias), MEETING_ACTIVITY);
    }

    /** Create an aliased <code>meeting_activity</code> table reference */
    public MeetingActivity(Name alias) {
        this(alias, MEETING_ACTIVITY);
    }

    /** Create a <code>meeting_activity</code> table reference */
    public MeetingActivity() {
        this(DSL.name("meeting_activity"), null);
    }

    public <O extends Record> MeetingActivity(
            Table<O> child, ForeignKey<O, MeetingActivityRecord> key) {
        super(child, key, MEETING_ACTIVITY);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<MeetingActivityRecord> getPrimaryKey() {
        return Keys.PK_MEETING_ACTIVITY;
    }

    @Override
    public List<UniqueKey<MeetingActivityRecord>> getKeys() {
        return Arrays.<UniqueKey<MeetingActivityRecord>>asList(Keys.PK_MEETING_ACTIVITY);
    }

    @Override
    public MeetingActivity as(String alias) {
        return new MeetingActivity(DSL.name(alias), this);
    }

    @Override
    public MeetingActivity as(Name alias) {
        return new MeetingActivity(alias, this);
    }

    /** Rename this table */
    @Override
    public MeetingActivity rename(String name) {
        return new MeetingActivity(DSL.name(name), null);
    }

    /** Rename this table */
    @Override
    public MeetingActivity rename(Name name) {
        return new MeetingActivity(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
